// <auto-generated />
using System;
using EFCore_Mod3.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EFCore_Mod3.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20181217175126_Estudiante_Detalle")]
    partial class Estudiante_Detalle
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EFCore_Mod3.Models.Contacto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("EstudianteId");

                    b.Property<string>("Nombre");

                    b.Property<string>("Relacion");

                    b.HasKey("Id");

                    b.HasIndex("EstudianteId");

                    b.ToTable("Contactos");
                });

            modelBuilder.Entity("EFCore_Mod3.Models.Estudiante", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("FechaNacimiento");

                    b.Property<string>("Nombre");

                    b.HasKey("Id");

                    b.ToTable("Estudiantes");

                    b.HasData(
                        new { Id = 25, FechaNacimiento = new DateTime(1985, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified), Nombre = "Data Seed" },
                        new { Id = 26, FechaNacimiento = new DateTime(1995, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified), Nombre = "Data Seed2" }
                    );
                });

            modelBuilder.Entity("EFCore_Mod3.Models.EstudianteDetalle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("EstudianteId");

                    b.Property<string>("Identificacion");

                    b.HasKey("Id");

                    b.HasIndex("EstudianteId")
                        .IsUnique();

                    b.ToTable("EstudianteDetalles");
                });

            modelBuilder.Entity("EFCore_Mod3.Models.Contacto", b =>
                {
                    b.HasOne("EFCore_Mod3.Models.Estudiante", "Estudiante")
                        .WithMany("Contactos")
                        .HasForeignKey("EstudianteId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("EFCore_Mod3.Models.EstudianteDetalle", b =>
                {
                    b.HasOne("EFCore_Mod3.Models.Estudiante")
                        .WithOne("Detalle")
                        .HasForeignKey("EFCore_Mod3.Models.EstudianteDetalle", "EstudianteId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
